---
- name: "[NGINX] Creating directory"
  ansible.builtin.file:
    state: directory
    path: /www/data
    owner: rafael
    group: rafael
    mode: '0644'
  become: true

- name: "[NGINX] Copy static contect"
  ansible.builtin.copy:
    src: index.html
    dest: /www/data/index.html
    owner: rafael
    group: rafael
    mode: '0644'
  become: true

- name: "[NGINX] Pulling container image"
  community.docker.docker_image:
    name: nginx
    source: pull

- name: "[NGINX] Starting container"
  community.docker.docker_container:
    # user: webserver
    name: webserver
    image: nginx:latest
    state: started
    recreate: true
    restart_policy: always
    ports:
      - "80:80"
    mounts:
      - type: "bind"
        read_only: true
        source: "/www/data/index.html"
        target: "/usr/share/nginx/html/index.html"
