- name: "[SSH] Ensure the .ssh directory exists"
  file:
    path: /home/{{ ansible_user }}/.ssh
    state: directory
    mode: '0700'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: "[SSH] Generate SSH key pair"
  command: ssh-keygen -t rsa -b 2048 -f /home/{{ ansible_user }}/.ssh/id_rsa -q -N ""
  args:
    creates: /home/{{ ansible_user }}/.ssh/id_rsa
  become: true
  become_user: "{{ ansible_user }}"

- name: "[SSH] Read the public key"
  slurp:
    src: /home/{{ ansible_user }}/.ssh/id_rsa.pub
  register: ssh_public_key

