---
- name: "[AD] Install Active Directory Domain Services (AD DS) feature"
  win_feature:
    name: AD-Domain-Services
    state: present

- name: "[AD] Promote server to Domain Controller"
  microsoft.ad.domain:
    safe_mode_password: "{{ ad_safe_mode_password }}"
    domain_admin_user: "{{ ad_admin_name }}"
    domain_admin_password: "{{ ad_admin_password }}"
    register: domain_install

- name: "[AD] Reboot host if install requires it"
  ansible.windows.win_reboot:
  when: domain_install.reboot_required
