---
- name: "[NGINX] Creating conf directory"
  ansible.builtin.file:
    state: directory
    path: /nginx/conf
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: true

- name: "[NGINX] Generate configuration"
  ansible.builtin.template:
    src: nginx.conf.j2 
    dest: /nginx/conf/nginx.conf
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: true

- name: "[NGINX] Creating data directory"
  ansible.builtin.file:
    state: directory
    path: /nginx/data
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: true

- name: "[NGINX] Copying static contect"
  ansible.builtin.copy:
    src: index.html
    dest: /nginx/data/index.html
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: true

- name: "[NGINX] Pulling container image"
  community.docker.docker_image:
    name: nginx
    source: pull

- name: "[NGINX] Starting container"
  community.docker.docker_container:
    name: nginx
    image: nginx:latest
    state: started
    recreate: true
    restart_policy: always
    ports:
      - "80:80"
    mounts:
      - type: "bind"
        source: "/nginx/data/index.html"
        target: "/usr/share/nginx/html/index.html"
      - type: "bind"
        source: "/nginx/conf/nginx.conf"
        target: "/etc/nginx/nginx.conf"
