---
# - name: "[NGINX] Creating service user"
#   ansible.builtin.user:
#     name: webserver
#     shell: /bin/false
#   become: true

- name: "[NGINX] Creating conf directory"
  ansible.builtin.file:
    state: directory
    path: /www/conf
    owner: rafael
    group: rafael
    mode: '0644'
  become: true

- name: "[NGINX] Generate configuration"
  ansible.builtin.template:
    src: nginx.conf.j2 
    dest: /www/conf/nginx.conf
    owner: rafael
    group: rafael
    mode: '0644'
  become: true

- name: "[NGINX] Creating data directory"
  ansible.builtin.file:
    state: directory
    path: /www/data
    owner: rafael
    group: rafael
    mode: '0644'
  become: true

- name: "[NGINX] Copy static contect"
  ansible.builtin.copy:
    src: index.html
    dest: /www/data/index.html
    owner: rafael
    group: rafael
    mode: '0644'
  become: true

- name: "[NGINX] Pulling container image"
  community.docker.docker_image:
    name: nginx
    source: pull

- name: "[NGINX] Starting container"
  community.docker.docker_container:
    # user: webserver
    name: webserver
    image: nginx:latest
    state: started
    recreate: true
    restart_policy: always
    ports:
      - "80:80"
    mounts:
      - type: "bind"
        source: "/www/data/index.html"
        target: "/usr/share/nginx/html/index.html"
      - type: "bind"
        source: "/www/conf/nginx.conf"
        target: "/etc/nginx/nginx.conf"
