---
# - name: "[WINDOWS] Install Active Directory and Certificate Services"
#   hosts: windows
#   roles:
#     - active-directory
    # - certificate-services

- name: "[LINUX] Deploying services stack"
  hosts: linux
  roles:
    - unattended-upgrade
    - docker
    - splunk
    - syslog-ng
    - nginx
